### ISSUE TITLE
[feature] 식재료 교환 채팅 구현

### ISSUE THREAD

**Issue by younghyun-j** [HomeChefHub/refooding-be#38]
> 💁‍♂️ GUIDE
> 1. 집중하기 위해 작은 단위로 진행하기
> 2. 하나의 이슈에 반영되는 PR 당 코드의 변경은 300줄이 넘어가지 않도록 노력하기

## 📝 Description
- 식재료 교환 채팅 구현

## ✅ TODO
- [x] 엔티티 및 연관관계 설정
- [x] sockjs 의존성 추가 및 설정
- [x] 채팅방 생성 API
- [x] 채팅방 목록 조회 API
- [x] 채팅메시지 생성 API
- [ ] 채팅방 상세 조회 API
- [x] 채팅방 삭제(나가기) API

## 💡 ETC
작업을 진행하면서 발생한 문제나 고려해야 할 기타 사항을 작성해주세요.
